config/routes.rb
require 'subdomain'

Profquotes::Application.routes.draw do
  
  match '/tweet/submit' => 'tweet#submit', :as => "submit"
  match '/tweet/submit_retweet' => 'tweet#submit_retweet', :as => "submit_retweet"
  match '/tweet/disable' => 'tweet#disable', :as => "disable"
  match '/tweet/vote' => 'tweet#vote', :as => "vote"
  match '/tweet/change_status' => 'tweet#change_status', :as => "change_status"
  match '/tweet/ask_to_tweet' => 'tweet#ask_to_tweet', :as => "ask_to_tweet"
  match '/tweet/more_tweets' => 'tweet#more_tweets'
    
  match '/signup' => "home#signup", :as => "signup"

  match '/t/:id' => "tweet#show", :as => "show"

  match '/login' => 'sessions#new', :as => "login"
  match '/logout' => 'sessions#destroy', :as => "logout"
  match '/oauth_callback' => 'sessions#oauth_callback', :as => "oauth_callback"

  resources :tweet, :feed, :session

  constraints(Subdomain) do
    match 'more_tweets' => "feed#more_tweets"
    match '/' => "feed#show", :as => :feed_root
    match 'edit' => "feed#edit", :as => :edit_feed
  end

  
  match '/:controller(/:action(/:id))'
  root :to => "home#index"
end

app/models/feed.rb
class Feed
  include MongoMapper::Document
  plugin MongoMapper::Plugins::Timestamps 
  
  belongs_to :user
  has_many :tweets

  attr_protected  :old_id
  
  key :user_id, ObjectId, :index => true
  key :admin_users, String, :default => ""
  key :old_id, Integer
  key :allow_retweets, Boolean,:default => false
  key :anonymous_votes, Boolean,:default => true
  key :allow_long_messages, Boolean,:default => false
  key :description, String,:default => ""
  key :light_default_status, Integer,:default => 1
  key :tweet_schedule, String,:default => ""
  key :submit_note, String,:default => ""
  key :tag_enabled, Boolean,:default => false
  key :tag_title, String,:default => "Tag"
  key :allow_long_tweets, Boolean,:default => false
  key :allow_anonymous_submits, Boolean,:default => false
  key :facebook_page_url, String, :default => ""
  timestamps! 

  def is_admin( user )
    
    if !user
      return false
    elsif (user == self.user)
      return true
    else
      self.admin_users.split(",").each do |a|
        if a.strip == user.login or a.strip == ("@" + user.login)
          return true
        end
      end
    end

    return false
  end

  def schedule_size
    scheduled_tweets = self[:tweet_schedule].split(',')

    if scheduled_tweets.size == 0
      " not scheduled to be posted"
    elsif scheduled_tweets.size == 1
      " posted once per day"
    else
      " posted #{scheduled_tweets.size} times per day "
    end
  end

  def self.find_by_subdomain( subdomain )
    user = User.find_by_login( subdomain )
    user.feed
  end
  
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  # GET /feed
  # GET /feed.xml

  before_filter :feed_check_admin, :only => :edit

  def feed_check_admin
    if !@current_feed.is_admin( current_user )
      redirect_to "/"
    end
  end

  def show

    load_common_lists_for_feed( @current_feed )
    @tweet = Tweet.new
    @tweet.tag = session[:school_name] unless session[:school_name].nil?
  end

  def more_tweets
    feed = Feed.find(params[:feed_id])
    @list_type = params[:type]
    @offset = params[:offset].to_i

    if params[:type] == 'new_tweets'
      if current_user and feed.is_admin( current_user )
        @tweets = Tweet.find_all_newest_twenty_for_feed( feed, @offset )
      else
        @tweets = Tweet.find_newest_twenty_for_feed( feed, @offset )
      end
    elsif params[:type] == 'best_tweets'
      @tweets = Tweet.find_best_for_feed( feed , @offset )
    elsif params[:type] == 'top_tweets'
      @tweets = Tweet.find_top_twenty_for_feed( feed, @offset )
    end

    @tweets = nil if @tweets.nil?


    respond_to do |format|
      format.html { }
      format.js{ render :action => 'show_more_tweets'}
    end
  end

  # GET /feed/1/edit
  def edit
    @feed = @current_feed
  end


  # PUT /feed/1
  # PUT /feed/1.xml
  def update
    @feed = Feed.find(params[:id])
    @feed.update_attributes(params[:feed])
    
    if @feed.save
      flash[:notice] = 'Feed was successfully updated.'
    else
      flash[:notice] = 'Feed save error'
    end
    respond_to do |format|
      format.html { render :action => "edit" }
    end
  end
end


def submit
    if current_user && current_user[:available_nominations].to_i > 0

      raw_tweet = current_user.twitter.get("/statuses/show/#{params['tweet_id']}")
      raw_tweet['tweet_id'] = raw_tweet['id'] #to match tweet model

      feed = Feed.find_by_username_or_create( raw_tweet['user']['screen_name'], current_user )
      @tweet = Tweet.find_or_create( raw_tweet, feed, current_user )

      if session[:recent_nominees].nil?
        session[:recent_nominees] = Array.new
      elsif session[:recent_nominees].size > 10
        session[:recent_nominees].delete_at( 0 )
      end

      add_vote_to_history( @tweet.id, current_user )
      session[:recent_nominees].push( @tweet.tweet_id )
      current_user.save
    elsif current_user
      flash[:notice] = "You have run out available nominations for today, please come back tomorrow!"
    else
      #not signed in
    end

    respond_to do |format|
      format.html { redirect_to :action=>"nominate" }
      format.js
    end

end

app/helpers/feed_helper.rb
module FeedHelper

  def light_status_show( quote )
    status_html = "<span class='status_indicators'>"

    if quote.traffic_light == 0
      status_html += "<span class='status_indicator initial_lit red_indicator red_on' onclick=''></span>"
    else
      status_html += "<span class='status_indicator red_indicator red_off' onclick=''></span>"
    end

    if quote.traffic_light == 1
      status_html += "<span class='status_indicator initial_lit yellow_indicator yellow_on' onclick=''></span>"
    else
      status_html += "<span class='status_indicator yellow_indicator yellow_off' onclick=''></span>"
    end

    if quote.traffic_light == 2
      status_html += "<span class='status_indicator initial_lit green_indicator green_on' onclick=''></span>"
    else
      status_html += "<span class='status_indicator green_indicator green_off' onclick=''></span>"
    end
    status_html += "</span>"

    return status_html
  end

  def tweet_now_button(tweet)
    return unless @current_feed.is_admin( current_user )
    return unless tweet.live_quote != 2
    
    status_html = "<span class='tweet_now'>"
    status_html += link_to "Tweet Now", :controller=>"tweet", :action=>"tweet_now", :id=>tweet.id
    return status_html + "</span>"
  end

end

app/views/feed/_main_tweets.erb
<% if @show_ads %>
  <div id="top_ads" style="text-align:center;">
    <script type="text/javascript"><!--
    google_ad_client = "ca-pub-7840601014474638";
    /* feedladder top middle */
    google_ad_slot = "2575334559";
    google_ad_width = 468;
    google_ad_height = 60;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
  </div>
<% end %>

<div class="box">
    <ul id="tabMenu">
      <li class="tabstop selected left"><!----></li>
      <li class="tabsbestof center "><!----></li>
      <li class="tabsnew right"><!----></li>
    </ul>

    <div class="boxTop"><!----></div>
    <div class="boxBody">
    <div id="tabstop" class="show0 tweet_panel">
      <ul id="top_tweets" class='tweets'>
        <%= render :partial => "tweet/tweet", :collection =>@top_tweets %>
      </ul>

      <%= render :partial => "tweet/show_more_box", :locals => {:type => "top_tweets"} %>

    </div>

    <div id="tabsbestof"  class="show1 tweet_panel">
      <ul id="best_tweets" class='tweets'>
        <%= render :partial => "tweet/tweet", :collection =>@tweet_best %>
      </ul>

      <%= render :partial => "tweet/show_more_box", :locals => {:type => "best_tweets"} %>
    </div>

    <div id="tabsnew" class="show2 tweet_panel">
      <ul id="new_tweets" class='tweets'>
        <%= render :partial => "tweet/tweet", :collection => @new_tweets %>
      </ul>
      <%= render :partial => "tweet/show_more_box", :locals => {:type => "new_tweets"} %>
    </div>

  </div>

</div>
<div class="boxBottom"><!----></div>

app/views/feed/edit.html.erb
<style type="text/css">
      #demo-frame > div.demo { padding: 10px !important; }
      #times span {
              height:120px; float:left; margin:15px
      }
</style>


<div class="left_side">
  <h1>Editing feed</h1>

  <%= form_for @feed, :as => :feed do |f| %>
     <%= @feed.errors.full_messages %>

    <h2>Info</h2>

    <p>
      <%= f.label :description %><br />
      <%= f.text_area :description , :size => "50x5" %>
    </p>

    <p>
      <%= f.label :facebook_page_url %><br />
      <%= f.text_area :facebook_page_url, :size => "50x5" %>
    </p>

    <p>
      <%= f.check_box :tag_enabled %>Allow tags<br/>
      <div id="tag_title" style="display:none;">
        <%= f.label :tag_title %><br />
        <%= f.text_field :tag_title %>
      </div>
    </p>

    <h2>Rules</h2>

    <p>
       <%= f.select :light_default_status, [ ["Submissions from logged in users don't need admin approval",2], ["All new Tweets need admin approval",1] ]  %>
    </p>
    <!--
    <p>
      <%= f.select :anonymous_votes, [ ["Any user can vote",false],["Only signed in Users can vote",true] ]  %>
    </p>
    -->
    <p>
      <%= f.select :allow_retweets, [ ["Don't Allow Retweet Submissions",false],["Allow Retweet Submissions",true] ]  %>
    </p>

    <p>
      <%= f.select :allow_long_messages, [ ["Don't Allow Long Submissions",false],["Allow Long Submissions",true] ]  %>
    </p>
    <!--
     <p>
      <%= f.select :allow_long_tweets, [ ["Only allow Twitter-compliant submissions (140 character max)",0],["Allow longer submissions with links",1] ]  %>
    </p>
    -->
    <p>
      <%= f.select :allow_anonymous_submits, [ ["Users Must be Signed in to Submit",false],["Allow Anonymous Submits",true] ]  %>
    </p>

    <hr>

    <%= f.hidden_field :tweet_schedule %>


<div class="demo">

  <p class="ui-state-default ui-corner-all ui-helper-clearfix" style="padding:4px;">
  <span class="ui-icon" style="float:left; margin:-2px 5px 0 0;"></span>
  Number of Tweets Per Day (<span id="master_count"></span>)
  </p>

  <div id="master" style="width:260px; margin:15px;"></div>

  <p class="ui-state-default ui-corner-all" style="padding:4px;margin-top:4em;">
  <span class="ui-icon" style="float:left; margin:-2px 5px 0 0;"></span>
  Times for tweets
  </p>

  <div id="times">

  </div>

</div><!-- End demo -->
<div class="demo-description" style="clear:left;">

  <p id="show_times"></p>

</div><!-- End demo-description -->

<h2>Admins</h2>
<p>
  <span style="color:c0c0c0">Comma delimited twitter handle list (eg: @ev,@biz)</span><br />
  <%= f.text_field :admin_users %>
</p>

    <p>
      <%= f.submit 'Submit' %>
    </p>
  <% end %>

</div>
<script type="text/javascript">

  var schedule_values = new Array();

  function display_times(){
    var parsed_times = new Array();

    for (var i=0; i< schedule_values.length; i++){
      parsed_times.push( schedule_values[i] + ":00" );
    }

    $("#show_times").html("Tweets will go out at: " + parsed_times.join(",") );
    
  }

  function setup_time_bars(){
    $("#times").html("");

    for (var i=0; i < schedule_values.length; i++){
      $("<span id='schedule_" + i + "'>" + schedule_values[i] + "</span>").appendTo("#times");
    }

    $("#times > span").each(function() {
      // read initial values from markup and remove that
      var value = parseInt($(this).text());
      $(this).empty().slider({
        value: value,
        range: "min",
        animate: true,
        orientation: "vertical",
        min: 0,
        max: 23,
        slide:  function(event, ui) {
          var id = parseInt( $(this).attr("id").split("_")[1] );
          schedule_values[id] = ui.value;
          $("#feed_tweet_schedule").val( schedule_values.join(",") );
          display_times();
        },
        step: 1
      });
    });
    display_times();
  }

  $(function() {

   if ( $("#feed_tag_enabled").is(":checked") ){
      $("#tag_title").show();
    } else {
      $("#tag_title").hide();
    }

    $("#feed_tag_enabled").click(function(){
      if ( $(this).is(":checked") ){
        $("#tag_title").show();
      } else {
        $("#tag_title").hide();
      }
    });
    
    // setup master volume
    schedule_values = $("#feed_tweet_schedule").val().split(",");

    if (schedule_values.length == 1 && schedule_values[0] == ""){
      //split can't return a 0-length array
      schedule_values = new Array();
    }

    $("#master").slider({
      orientation: "horizontal",
      range: "min",
      animate: true,
      value:schedule_values.length,
      min: 0,
      max: 6,
      step: 1,
      slide:  function(event, ui) {
        $("#master_count").html(ui.value);
      },
      stop: function(event, ui) {
        while (ui.value > schedule_values.length){
          schedule_values.push( 12 );
        }
        while (ui.value < schedule_values.length){
          schedule_values.pop();
        }
        $("#feed_tweet_schedule").val( schedule_values.join(",") );
        setup_time_bars();
      }
    });
    
    $("#master_count").html(schedule_values.length);
    setup_time_bars();

  });
</script>

app/views/feed/show.html.erb
<% content_for :meta do %>
  <meta property="og:title" content='<%= @current_feed.user.name %>'/>
  <meta property="og:site_name" content='Feed Ladder'/>
  <meta property="og:type" content="website" />
<% end %>

<% content_for :css do %>
  <style type="text/css">
  .ui-helper-reset {
    font-size:13px;
    line-height:0.5;
  }
  .ui-tabs .ui-tabs-nav {
    background: none;
    border-bottom:1px solid #4297D7;
    border-top:none;
    border-left:none;
    border-right:none;
  }

  .ui-tabs .ui-tabs-panel {
    padding: 1em 0.3em;
  }

</style>
<% end %>

  <div class="box">
    <div class="boxCap"><!----></div>
      <div class="box_static_body">
        <% if current_user or @current_feed.allow_anonymous_submits %>
          <%= render :partial => "tweet/publisher", :locals => {:expanded_publisher => true}  %>
        <% else %>
            <div id="signup_copy" style="padding: 2px 0 2px 0;">
              <div>
                Login to submit:
              </div>
              <div>
                <%= link_to( image_tag( "twitter-dark.png" ), login_path ) %>
              </div>
            </div>
        <% end %>
      </div>
    <div class="boxBottom"><!----></div>
  </div>


<%= render :partial => "feed/main_tweets" %>

app/views/feed/show_more_tweets.js.erb
$("#<%= raw @list_type %>").append("<%= escape_javascript( render :partial => "tweet/tweet", :collection =>@tweets ) %>")

$("#<%= raw @list_type %>_offset").val('<%= raw @offset+@tweets.length %>')

$("#<%= raw "#{@list_type}_box" %> a").show();       

$("#<%= raw "#{@list_type}_spinner" %>").hide();

<% if !@current_feed.nil? and current_user and @current_feed.is_admin( current_user ) %>
    $(".status_indicators").show(); //hidden by default
<% end %>