config/routes.rb
require 'subdomain'

Profquotes::Application.routes.draw do
  
  match '/tweet/submit' => 'tweet#submit', :as => "submit"
  match '/tweet/submit_retweet' => 'tweet#submit_retweet', :as => "submit_retweet"
  match '/tweet/disable' => 'tweet#disable', :as => "disable"
  match '/tweet/vote' => 'tweet#vote', :as => "vote"
  match '/tweet/change_status' => 'tweet#change_status', :as => "change_status"
  match '/tweet/ask_to_tweet' => 'tweet#ask_to_tweet', :as => "ask_to_tweet"
  match '/tweet/more_tweets' => 'tweet#more_tweets'
    
  match '/signup' => "home#signup", :as => "signup"

  match '/t/:id' => "tweet#show", :as => "show"

  match '/login' => 'sessions#new', :as => "login"
  match '/logout' => 'sessions#destroy', :as => "logout"
  match '/oauth_callback' => 'sessions#oauth_callback', :as => "oauth_callback"

  resources :tweet, :feed, :session

  constraints(Subdomain) do
    match 'more_tweets' => "feed#more_tweets"
    match '/' => "feed#show", :as => :feed_root
    match 'edit' => "feed#edit", :as => :edit_feed
  end

  
  match '/:controller(/:action(/:id))'
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :assert_login, :only => :profile

  def index
    
  end

  def profile
    @user = current_user
    @quotes = @user.tweets[0..19]
    redirect_to "/" unless !@user.nil?
  end

  def signup
    session['signup_catch'] = true
    if @next.nil?
      @next = "/"
    end
  end

  def about_us
  end

  def privacy_policy
  end

  def terms_of_service
  end

  def contact_us
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def live_quote_explanation( live_quote )
    case live_quote
      when 0
        return "No longer active"
      when 1
        return "Active"
      when 2
        return "Retweeted by ProfQuotes!"
    end

  end

  def like_href_destination( feed )
    if feed[:facebook_page_url].nil? or feed[:facebook_page_url] == ""
      "#{feed.user.login}.feedladder.com/"
    else
      feed[:facebook_page_url]
    end
  end

  def header_logo
    if @current_feed && @current_feed.user.login == "profquotes"
      image_tag "pq_logo.png"
    else
      image_tag "fl_logo.png"
    end

  end

end

app/views/home/_admin_panel.html.erb
<div class="latestNews_box"><!--start latestNews_box-->
  <div class="latest_bg">
    <div class="latest_top">
      <div class="latest_btm">
        <div class="content_latestNews_box">
            <%= link_to 'Admin Panel',edit_feed_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_ads.html.erb
<div class="latestNews_box"><!--start latestNews_box-->
  <div class="latest_bg">
    <div class="latest_top">
      <div class="latest_btm">
        <div class="content_latestNews_box" style="text-align:center;">

          <script type="text/javascript"><!--
          google_ad_client = "ca-pub-7840601014474638";
          /* feedladder right column */
          google_ad_slot = "1179836517";
          google_ad_width = 336;
          google_ad_height = 280;
          //-->
          </script>
          <script type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
          </script>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_feed_rules.html.erb
<div class="latestNews_box"><!--start latestNews_box-->
  <div class="latest_bg">
    <div class="latest_top">
      <div class="latest_btm">
        <div class="content_latestNews_box">
            <div>
              Tweets are <span style='color:green'><%= @current_feed.schedule_size %></span>
            </div>
            <div>
              <% if @current_feed[:allow_anonymous_submits] %>
                Submissions <span style='color:green'>can be made by anyone</span>
              <% else %>
                Submissions <span style='color:green'>must be made by logged in user</span>
              <% end %>
            </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_follow_twitter.html.erb
<div class="latestNews_box"><!--start latestNews_box-->
  <div class="latest_bg">
    <div class="latest_top">
      <div class="latest_btm">
        <div class="content_latestNews_box" style="text-align:center;">
            <%= link_to image_tag( "twitter_banner.jpg", :width => "300" ), "http://twitter.com/#{@current_feed.user.login}",:target => '_blank' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<div class="footer">
	<div id="cont_footer"><!--start cont_footer-->
		<div class="cont_footer_top" style="height:50px"><!--start cont_footer_top-->
			<div class="footer_mainCont" style="padding-top:0px"><!--start footer_mainCont-->
				<div class="all_link_footer" style="display:none;"><!--start all_link_footer-->
					<ul class="all_link_footer01">
						<li class="Competitions"><a href="#" title="Competitions">Competitions</a></li>
						<li><a href="#" title="Current Competitions">Current Competitions</a></li>
						<li><a href="#" title="Competition Rules">Competition Rules</a></li>
					</ul>
					<ul class="all_link_footer02">
						<li class="Competitions"><a href="#" title="Music">Music</a></li>
						<li><a href="#" title="New Music">New Music</a></li>
						<li><a href="#" title="Charts">Charts</a></li>
						<li><a href="#" title="Music Queries">Music Queries</a></li>
					</ul>
					<ul class="all_link_footer03">
						<li class="Competitions"><a href="#" title="Gigs &amp; Events">Gigs &amp; Events</a></li>
						<li><a href="#" title="Latest Events">Latest Events</a></li>
						<li><a href="#" title="Gig Guide">Gig Guide</a></li>
						<li><a href="#" title="Submit A Gig">Submit A Gig</a></li>
					</ul>
					<ul class="all_link_footer04">
						<li class="Competitions"><a href="#" title="Blog">Blog</a></li>
						<li><a href="#" title="Latest Posts">Latest Posts</a></li>
					</ul>
					<ul class="all_link_footer05">
						<li class="Competitions"><a href="#" title="Sitemap">Sitemap</a></li>
						<li><a href="#" title="Help Getting Around">Help Getting Around</a></li>
					</ul>
				</div><!--end all_link_footer-->
				<div class="sub_menu_footer" style="display:none;">
					<ul>
						<li class="sub_menu_footerFst"><a href="#" title="Home">Home</a></li>
						<li><%= link_to "privacy policy",{:controller=>"home", :action=>"privacy_policy"} %></li>
						<li><%= link_to "about us", {:controller=>"home", :action=>"about_us"} %></li>
						<li><%= link_to "contact", {:controller=>"home", :action=>"contact_us"} %></li>
						<li><%= link_to "terms of service", {:controller=>"home", :action=>"terms_of_service"} %></li>
					</ul>
				</div>
			</div><!--end footer_mainCont-->
		</div>
		<!--end cont_footer_top-->
		<div id="foooter_low" style="display:none;">
			<div class="txt_ftr_low">© 2010-2011 Feedladder All rights reserved</div>
			<div class="foooter_low_rgt">
            	<ul>
				<li><a href="#" title="Digg" class="pic01">Digg</a></li>
				<li><a href="#" title="Delicious" class="pic02">Delicious</a></li>
				<li><a href="#" title="Facebook" class="pic03">Facebook</a></li>
				<li><a href="#" title="reddit" class="pic04">reddit</a></li>
                </ul>
			</div>
		</div>
	</div><!--end cont_footer-->
</div>

app/views/home/_header.html.erb
<div id="topmenu-area"><!--start topmenu-area-->
  <div class="top_rgt">
    <%= render :partial => "home/login_badge" %>
  </div>
</div><!--end topmenu-area-->
<div class="logo_area"><!--start logo_area-->
  <div id="logo">
    <%= header_logo %>
  </div>
  <div id="menu-area">
    <ul>
      <% if @current_feed %>
        <li class="home"><%= link_to "Home", feed_root_url(:subdomain => @current_feed.user.login), :class => 'glow' %></li>
      <% else %>
        <li class="home"><%= link_to "Home", feed_root_url(:subdomain => false), :class => 'glow' %></li>
      <% end %>
      <% if false #current_user %>
        <li class="my_page"><%= link_to "My Page", profile_path, :class => 'glow' %></li>
      <% end %>
    </ul>
  </div>
</div><!--end logo_area-->

app/views/home/_new_submission_popup.html.erb
<div id="dialog-modal">
    <table>
      <tr>
        <td colspan="2">
          <span class="popup_text">
            Submission successful!  It will need to be approved to show on main page, but in the mean time you can share it with others.
          </span>
        </td>
      </tr>
      <tr><td colspan="2"><br/></tr>
      <tr>
        <td style="text-align: right;">
          <%= link_to image_tag("facebook-share-icon.gif"), "http://facebook.com/sharer.php?u=http://#{@current_feed.user.login}.feedladder.com/t/#{@new_tweet.id}",:class=>"auto_close",:target => '_blank' %>
        </td>
        <td>
          <%= link_to image_tag("twitter-share-icon.jpg"), "http://twitter.com/?status=#{@new_tweet.tweet_share(true)}",:class=>"auto_close", :target => '_blank'  %>
        </td>
      </tr>
    </table>
</div>

app/views/home/_right_column.html.erb
<% if @current_feed %>
  <%= render :partial => "home/intro_panel" %>

  <% if @show_ads %>
    <%= render :partial => "home/ads" %>
  <% end %>
  <!-- render :partial => "home/feed_rules" -->
  <%= render :partial => "home/follow_twitter" %>

  <% if @current_feed.is_admin( current_user ) %>
    <%= render :partial => "home/admin_panel" %>
  <% end %>
<% else %>
  <%= render :partial => "home/top_feeds" %>
<% end %>

app/views/home/_top_feeds.html.erb
<div class="latestNews_box"><!--start latestNews_box-->
  <div class="latest_bg">
    <div class="latest_top">
      <div class="latest_btm">
        <div class="content_latestNews_box">
          <h2>Available Feeds</h2>
             
             <% @top_feeds.each do |feed| %>
              <hr>
              <table border="0" cellspacing="2">
                <tr>
                  <td style="padding: 0 5px 5px 0;" rowspan="2"><%= image_tag feed.user[:profile_image_url]  %></td>
                  <td>
                    <span style="font-size: 1.17em;font-weight: bold;">
                      <%=  link_to h(feed.user.name), feed_root_url(:subdomain => feed.user.login) %>
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>Followers: <%= feed.user[:followers_count]  %></td>
                </tr>
              </table>
             <% end %>
             <hr>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<h1>Home#contact_us</h1>
<p>Find me in app/views/home/contact_us.html.erb</p>

app/views/home/index.html.erb
  <div class="box">
    <div class="boxCap"><!----></div>
      <div class="box_static_body">
        Welcome to Feed Ladder!
      </div>
    <div class="boxBottom"><!----></div>
  </div>

app/views/home/privacy_policy.html.erb
<h1>Home#privacy_policy</h1>
<p>Find me in app/views/home/privacy_policy.html.erb</p>

app/views/home/profile.html.erb
<div class="box">
  <div class="boxCap"><!----></div>
    <div class="box_static_body">
      <h2>Your Submitted quotes</h2>

      <ul class='quotes'>
          <%  @quotes.each_with_index do |quote, i|%>
            <%= render :partial => "quote/quote", :locals => {:quote => quote, :i => i } %>
          <% end %>
      </ul>
    </div>
  <div class="boxBottom"><!-- --></div>
</div>

app/views/home/terms_of_service.html.erb
<h1>Home#terms_of_service</h1>
<p>Find me in app/views/home/terms_of_service.html.erb</p>